language: node_js

stages:
  - lint
  - build
  - test
  - release

notifications:
  email: false

node_js: 10.0.0

jobs:
  include:
    - stage: lint
      script:
        - npm run lint

    - stage: build
      script:
        - npm run build

    - stage: test
      name: 'Unit Tests'
      script:
        - npm run test:unit

    - stage: test
      name: 'Integration Tests'
      before_script:
        ## Spin up container
        - cd test/docker/
        - docker-compose -f docker-compose.test.yml up -d

        ## Test for liveness
        # - docker exec -it gitlab bash -lc 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' http://localhost/-/readiness)" != "200" ]]; do sleep 5; done'
        - sleep 240

        - export PERSONAL_ACCESS_TOKEN=$(docker exec -it gitlab bash -lc 'printf "%q" "${PERSONAL_ACCESS_TOKEN}"')
        - export GITLAB_URL=$(docker exec -it gitlab bash -lc 'printf "%q" "${GITLAB_URL}"')
        - echo $GITLAB_URL
        - echo $PERSONAL_ACCESS_TOKEN
      script:
        - npm run test:integration

    - stage: release
      script:
        - npm run release
